include("baleen")
include("baleen-avro-generator")
include("baleen-base-schema-generator")
include("baleen-csv")
include("baleen-db:baleen-jdbc")
include("jsonschema-model")
include("baleen-jsonschema-generator")
include("jsonschema-baleen-generator")
include("baleen-json-jackson")
include("baleen-xml")
include("baleen-xsd-generator")
include("baleen-kotlin:baleen-kotlin-api")
include("baleen-kotlin:baleen-kotlin-kapt")
include("baleen-kotlin:baleen-kotlin-generator")
include("baleen-kotlin:example")
include("baleen-poet")
include("baleen-printer:baleen-printer-csv")
include("baleen-printer:baleen-printer-html")
include("baleen-printer:baleen-printer-java-logger")
include("baleen-printer:baleen-printer-text")
include("baleen-script")

rootProject.name = "baleen"
